#
name: Create and publish a Docker image

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
    paths-ignore:
      - 'akash-llm-gateway/**'      

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GH_PAT` for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          default_bump: patch
          default_prerelease_bump: patch
          
      - name: Build and push Docker image for main branch
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_GA_ID=${{ vars.NEXT_PUBLIC_GA_ID }}
            NEXT_PUBLIC_VERSION=${{ steps.tag_version.outputs.new_version }}
            NEXT_PUBLIC_WEBSOCKET_URLS=${{ vars.NEXT_PUBLIC_WEBSOCKET_URLS }}
            DESCRIPTION=${{ steps.tag_version.outputs.changelog }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_version }}

      - name: Build and push Docker image for non-main branches
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_GA_ID=${{ vars.NEXT_PUBLIC_GA_ID }}
            NEXT_PUBLIC_VERSION=${{ github.ref_name }}
            NEXT_PUBLIC_WEBSOCKET_URLS=${{ vars.NEXT_PUBLIC_WEBSOCKET_URLS }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}